name: wazo-call-distribution-plugin
namespace: quintana
version: 0.0.1
author: Piotr
display_name: Plugin Call Distribution
plugin_format_version: 1
min_wazo_version: 25.02
tags:
  - call_distribution
  - demo
#depends:
#  - name: foo
#    namespace: foocorp
debian_depends:
  - vim
homepage: https://github.com/darkhosre34/call-distribution-plugin
